replicaCount: 1

image:
  repository: ghcr.io/mikigbo/user-access
  tag: "0.0.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: user-access.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

secret:
  name: user-access-secret
  data: {}

config:
  PORT: "80"
  setting2: "value2"
