apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-access
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mikigbo/user-access-control'
    targetRevision: cd-release
    path: helmchart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: appnamespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 2
